# -*- coding: utf-8 -*-
"""cps843.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lFGjYipbE0MPZtidRNwfnscnyfy8evX

GitHub repo:
https://github.com/ayanmali/cps843-assignment
"""

from google.colab import drive
drive.mount('/content/drive')

"""Run the script `extract_chars.py` on your local machine to produce the cleaned training and validation datasets of characters.

ZIP the `char_train/`, `char_val_/`, `word_train/`, and `word_val/` directories on your local machine.

Upload the char_train.zip, char_val.zip, word_train.zip, and word_val.zip files from your local machine into the notebook.
"""

# Unzips the zipped training and validation sets
import zipfile

for zip_file in ['char_train.zip', 'char_val.zip']:
    with zipfile.ZipFile(zip_file, 'r') as z:
        z.extractall('.')

"""# Models"""

TARGET_SIZE = (24, 24)

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

"""## LeNet"""

class LeNetCharClassifier(nn.Module):
    """
    LeNet-5 CNN for character recognition.

    Architecture:
    - Input: 24x24 grayscale images (1 channel)
    - Output: 52 classes (26 uppercase + 26 lowercase letters)

    Five trainable layers:
    1. Conv1: 24 filters, 3x3 kernel
    2. Conv2: 48 filters, 5x5 kernel
    3. FC1: Fully connected layer (384 units)
    4. FC2: Fully connected layer (256 units)
    5. Output: Fully connected layer (num_classes)

    Design:
    - 2 conv layers w Max Pooling for spatial feature extraction
    - Sigmoid activation function for conv layers
    - Two FC layers
    - Flattening layer to convert feature maps to 2D array before FC layers
    """
    def __init__(self, num_classes: int = 52):
        super(LeNetCharClassifier, self).__init__()

        # First convolutional layer
        # Input: (batch_size, 1, 24, 24)
        # Output: (batch_size, 24, 22, 22) with 3x3 kernel, padding=0
        self.conv1 = nn.Conv2d(1, 24, kernel_size=3, stride=1, padding=0)

        # First Max Pooling layer
        # Input: (batch_size, 24, 22, 22)
        # Output: (batch_size, 24, 11, 11)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        # Second convolutional layer
        # Input: (batch_size, 24, 11, 11)
        # Output: (batch_size, 48, 7, 7) with 5x5 kernel, padding=0
        self.conv2 = nn.Conv2d(24, 48, kernel_size=5, stride=1, padding=0)

        # Second Max Pooling layer
        # Input: (batch_size, 48, 7, 7)
        # Output: (batch_size, 48, 3, 3)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)

        # Flattening layer (implicit in forward pass using view)
        # After pool2: (batch_size, 48, 3, 3) -> (batch_size, 48*3*3) = (batch_size, 432)

        # First fully connected layer
        # Input: (batch_size, 432)
        # Output: (batch_size, 384)
        self.fc1 = nn.Linear(48 * 3 * 3, 384)

        # Second fully connected layer
        # Input: (batch_size, 384)
        # Output: (batch_size, 256)
        self.fc2 = nn.Linear(384, 256)

        # Output layer (third fully connected layer)
        # Input: (batch_size, 256)
        # Output: (batch_size, num_classes)
        self.fc3 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.conv1(x)  # -> (batch_size, 24, 22, 22)
        x = torch.sigmoid(x)

        x = self.pool1(x)  # -> (batch_size, 24, 11, 11)

        x = self.conv2(x)  # -> (batch_size, 48, 7, 7)
        x = torch.sigmoid(x)

        x = self.pool2(x)  # -> (batch_size, 48, 3, 3)

        # (batch_size, 48, 3, 3) -> (batch_size, 48*3*3) = (batch_size, 432)
        x = x.view(x.size(0), -1)

        x = self.fc1(x)  # -> (batch_size, 384)
        x = torch.sigmoid(x)  # LeNet typically uses sigmoid for FC layers too

        x = self.fc2(x)  # -> (batch_size, 256)
        x = torch.sigmoid(x)

        x = self.fc3(x)  # -> (batch_size, num_classes)

        return x


def create_lenet_model(num_classes: int = 52) -> LeNetCharClassifier:
    model = LeNetCharClassifier(num_classes=num_classes)

    # Initialize weights
    _initialize_weights(model)

    return model


def _initialize_weights(model: nn.Module):
    # Initialize model weights using Xavier/Glorot initialization
    for m in model.modules():
        if isinstance(m, nn.Conv2d):
            # Xavier initialization for sigmoid activation
            nn.init.xavier_uniform_(m.weight)
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.Linear):
            # Xavier initialization for sigmoid activation
            nn.init.xavier_uniform_(m.weight)
            nn.init.constant_(m.bias, 0

"""## VGG-16"""

class VGGBlock(nn.Module):
    """
    multiple 3x3 convolutions followed by max pooling
    """
    def __init__(self, in_channels: int, out_channels: int, num_convs: int = 2):
        super(VGGBlock, self).__init__()

        layers = []

        # add multiple 3x3 convolutions
        for i in range(num_convs):
            layers.append(nn.Conv2d(
                in_channels if i == 0 else out_channels,
                out_channels,
                kernel_size=3,
                stride=1,
                padding=1,
                bias=False
            ))
            layers.append(nn.BatchNorm2d(out_channels))
            layers.append(nn.Sigmoid())

        # Add max pooling
        layers.append(nn.MaxPool2d(kernel_size=2, stride=2))

        self.block = nn.Sequential(*layers)

    def forward(self, x):
        return self.block(x)

# Categorical cross-entropy loss
class VGG16CharClassifier(nn.Module):
    def __init__(self, num_classes: int = 52):
        super(VGG16CharClassifier, self).__init__()

        # Block 1: 28x28 -> 14x14
        # 2 conv layers with 64 channels
        self.block1 = VGGBlock(1, 64, num_convs=2, use_pooling=True)

        # Block 2: 14x14 -> 7x7
        # 2 conv layers with 128 channels
        self.block2 = VGGBlock(64, 128, num_convs=2, use_pooling=True)

        # Block 3: 7x7 -> 3x3 (or use global avg pool)
        # 2 conv layers with 256 channels
        self.block3 = VGGBlock(128, 256, num_convs=2, use_pooling=True)

        # Global average pooling to reduce spatial dimensions to 1x1
        self.global_avg_pool = nn.AdaptiveAvgPool2d(1)

        # Classifier head
        self.dropout1 = nn.Dropout(0.2)
        self.fc1 = nn.Linear(256, 128)
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, x):
        # input: (batch_size, 1, 24, 24)
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)

        # Global average pooling: (batch_size, 256, 3, 3) -> (batch_size, 256, 1, 1)
        x = self.global_avg_pool(x)

        # Flatten: (batch_size, 256, 1, 1) -> (batch_size, 256)
        x = x.view(x.size(0), -1)

        # Classifier
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout1(x)

        x = self.fc2(x)

        return x


def create_vgg16_model(num_classes: int = 52):
    model = VGG16CharClassifier(num_classes=num_classes)

    # Initialize weights
    _initialize_weights(model)

    return model


def _initialize_weights(model: nn.Module):
    # Initialize model weights using Kaiming initialization
    for m in model.modules():
        if isinstance(m, nn.Conv2d):
            nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.BatchNorm2d):
            nn.init.constant_(m.weight, 1)
            nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.Linear):
            nn.init.normal_(m.weight, 0, 0.01)
            nn.init.constant_(m.bias, 0)

"""## CRNN"""

class CRNN(nn.Module):
    def __init__(self, num_classes, rnn_hidden_size=128, cnn_out_channels=256, dropout=0.35, num_rnn_layers=1):
        """
        num_classes: # of unique characters + 1 (for the CTC 'blank' token)
        rnn_hidden_size: hidden size for RNN layers
        cnn_out_channels: output channels for CNN backbone
        dropout: dropout probability
        """
        super(CRNN, self).__init__()
        self.rnn_hidden_size = rnn_hidden_size
        self.cnn_out_channels = cnn_out_channels
        self.dropout = dropout

        # Feature Extraction
        # rectangular pooling
        self.cnn = nn.Sequential(
            # First block: 1 -> 32 channels
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=(1, 2), stride=(1, 2)),

            # Second block: 32 -> 64 channels
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=(1, 2), stride=(1, 2)),

            # Third block: 64 -> 128 channels
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=(2, 1), stride=(2, 1)),

            # Fourth block: 128 -> 256 channels
            nn.Conv2d(128, cnn_out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(cnn_out_channels),
            nn.ReLU(inplace=True),

        )

        # Dropout after CNN
        self.cnn_dropout = nn.Dropout2d(dropout)

        # The input size to the RNN is (Channels * Height_after_pooling)
        # With rectangular pooling: H=32 -> H/2 = 16 (after third pooling)
        # Input Feature Dimension = cnn_out_channels * 16
        rnn_input_size = cnn_out_channels * 16

        # Sequence Modeling (RNN)
        # single-layer Bi-LSTM for less parameters
        self.rnn = nn.LSTM(
            input_size=rnn_input_size,
            hidden_size=rnn_hidden_size,
            num_layers=num_rnn_layers,  # Single layer to reduce parameters
            bidirectional=True,
            batch_first=False,  # (Sequence, Batch, Features)
            dropout=dropout if num_rnn_layers > 1 else 0  # Dropout only applies if num_layers > 1
        )

        # Dropout after RNN
        self.rnn_dropout = nn.Dropout(dropout)

        # Transcription/Classification
        # Maps the output of the Bi-LSTM (2 * hidden_size) to the number of classes (including blank)
        self.fc = nn.Linear(rnn_hidden_size * 2, num_classes)

    def forward(self, x):
        # forward pass through the CRNN

        # 1. CNN feature extraction
        # input x shape: (Batch, 1, H, W)
        conv_out = self.cnn(x)

        # apply dropout
        conv_out = self.cnn_dropout(conv_out)

        # 2. reshape for RNN

        # squeeze height dim into channels dim
        B, C, H, W = conv_out.size()

        # reshape to (batch, width, features) where features = C * H
        conv_out = conv_out.permute(0, 3, 1, 2)  # (B, W, C, H)
        conv_out = conv_out.contiguous().view(B, W, -1)  # (B, W, C*H)

        # final reshape to (Sequence_Length, Batch, Features)
        # sequence length corresponds to width (time-steps/character positions)
        rnn_input = conv_out.permute(1, 0, 2)  # (W, B, C*H)

        # 3. RNN sequence modeling
        rnn_output, _ = self.rnn(rnn_input)

        # apply dropout
        rnn_output = self.rnn_dropout(rnn_output)

        # 4. Final Classification
        output = self.fc(rnn_output)

        return output

"""# Training Character-Based Classifier"""

LABELS = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
]

import cv2
import numpy as np

def load_img(path: str) -> np.ndarray:
    """
    load image from path
    """
    return cv2.imread(path)

"""
Training pipeline for character classification using folder-based dataset structure.
Structure: char_{split}/{case}/{letter}/ where split is 'train' or 'val', case is 'cap' or 'lc', letter is A-Z or a-z.
"""
import os
import sys
from torch.utils.data import Dataset, DataLoader
from typing import List, Tuple
from tqdm import tqdm
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt

class FolderCharacterDataset(Dataset):
    def __init__(
        self,
        base_dir: str,
        split: str = "train",  # "train" or "val"
        target_size: Tuple[int, int] = TARGET_SIZE,
        transform=None,
    ):

        self.base_dir = base_dir
        self.split = split
        self.target_size = target_size
        self.transform = transform

        # Create label to index mapping
        self.label_to_idx = {char: idx for idx, char in enumerate(LABELS)}
        self.idx_to_label = {idx: char for char, idx in self.label_to_idx.items()}
        self.num_classes = len(LABELS)

        # Load all images from folder structure
        self.image_paths = []
        self.labels = []
        self.label_strings = []  # Store actual label strings for statistics
        self._load_images()

        print(f"Loaded {len(self.image_paths)} images for {self.split} split")
        print(f"Class distribution:")
        label_counts = {}
        for label_str in self.label_strings:
            label_counts[label_str] = label_counts.get(label_str, 0) + 1
        for label_str, count in sorted(label_counts.items()):
            print(f"  {label_str}: {count}")

    def _load_images(self):
        split_dir = os.path.join(self.base_dir, f"char_{self.split}")

        if not os.path.exists(split_dir):
            raise ValueError(f"Directory {split_dir} does not exist")

        # Iterate through case folders (cap, lc)
        for case in ["cap", "lc"]:
            case_dir = os.path.join(split_dir, case)
            if not os.path.exists(case_dir):
                continue

            # Iterate through letter folders
            for letter_folder in sorted(os.listdir(case_dir)):
                letter_path = os.path.join(case_dir, letter_folder)
                if not os.path.isdir(letter_path):
                    continue

                # map folder name to label
                # For 'cap' case, folder names are uppercase (A, B, C, ...)
                # For 'lc' case, folder names are lowercase (a, b, c, ...)
                label = letter_folder

                # Verify label is in our label set
                if label not in self.label_to_idx:
                    print(f"Warning: Label '{label}' not in LABELS, skipping folder {letter_path}")
                    continue

                # Load all images from this folder
                image_files = [f for f in os.listdir(letter_path)
                              if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

                for img_file in image_files:
                    img_path = os.path.join(letter_path, img_file)
                    self.image_paths.append(img_path)
                    self.labels.append(self.label_to_idx[label])
                    self.label_strings.append(label)

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):

        import cv2

        img_path = self.image_paths[idx]
        label_idx = self.labels[idx]

        # Load image
        img = load_img(img_path)
        if img is None:
            # If image fails to load, return a black image
            img = np.zeros((*self.target_size, 3), dtype=np.uint8)

        # Convert BGR to grayscale if image has 3 channels
        if len(img.shape) == 3:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # resize to target size if needed
        if img.shape[:2] != self.target_size:
            img = cv2.resize(img, (self.target_size[1], self.target_size[0]), interpolation=cv2.INTER_AREA)

        # Normalize to [0, 1]
        img_normalized = img.astype(np.float32) / 255.0

        # Convert to tensor and add channel dimension: (H, W) -> (1, H, W)
        image_tensor = torch.from_numpy(img_normalized).unsqueeze(0)

        # Apply transforms if provided
        if self.transform:
            image_tensor = self.transform(image_tensor)

        return image_tensor, label_idx


def train_epoch(model, dataloader, criterion, optimizer, device):
    #Train for one epoch
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in tqdm(dataloader, desc="Training"):
        images = images.to(device)
        labels = labels.to(device)

        # Forward pass
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass
        loss.backward()
        optimizer.step()

        # Statistics
        running_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(dataloader)
    epoch_acc = 100.0 * correct / total
    return epoch_loss, epoch_acc


def validate(model, dataloader, criterion, device):
    # validaiton accuracy
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in tqdm(dataloader, desc="Validating"):
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(dataloader)
    epoch_acc = 100.0 * correct / total
    return epoch_loss, epoch_acc


def plot_training_curves(
    train_losses: List[float],
    val_losses: List[float],
    train_accs: List[float],
    val_accs: List[float],
    save_path: str = "training_curves.png"
):

    epochs = range(1, len(train_losses) + 1)

    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    # Plot loss
    ax1.plot(epochs, train_losses, 'b-', label='Training Loss', linewidth=2)
    ax1.plot(epochs, val_losses, 'r-', label='Validation Loss', linewidth=2)
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('Loss', fontsize=12)
    ax1.set_title('Training and Validation Loss', fontsize=14)
    ax1.legend(fontsize=11)
    ax1.grid(True, alpha=0.3)

    # Plot accuracy
    ax2.plot(epochs, train_accs, 'b-', label='Training Accuracy', linewidth=2)
    ax2.plot(epochs, val_accs, 'r-', label='Validation Accuracy', linewidth=2)
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Accuracy (%)', fontsize=12)
    ax2.set_title('Training and Validation Accuracy', fontsize=14)
    ax2.legend(fontsize=11)
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()

    # Save plot
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\nTraining curves saved to: {save_path}")

    plt.close()


def save_model(model: nn.Module, model_path: str, metadata: dict = None):
    """
    Save a PyTorch model w/ metadata

    """
    os.makedirs(os.path.dirname(model_path), exist_ok=True)

    # Save model state dict and metadata
    save_dict = {
        'model_state_dict': model.state_dict(),
        'metadata': metadata or {}
    }

    torch.save(save_dict, model_path)
    print(f"Model saved to: {model_path}")


def train_model(
    base_dir: str,# = ".",
    model_type: str,#   = "lenet",  # "lenet", or "vgg16"
    loss_function: str,# = "cross_entropy"
    batch_size: int,#    = 32,
    num_epochs: int,#     = 20,
    learning_rate: float,# = 0.001,
    device,#    = None,
    model_save_path: str,#    = "saved_models/character_classifier.pth",
    plot_save_path: str,#    = "training_curves.png",
):

    # Set device
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(device)
    print(f"Using device: {device}")




    # Create datasets
    print("\nLoading training dataset...")
    train_dataset = FolderCharacterDataset(
        base_dir=base_dir,
        split="train",
        target_size=TARGET_SIZE
    )

    print("\nLoading validation dataset...")
    val_dataset = FolderCharacterDataset(
        base_dir=base_dir,
        split="val",
        target_size=TARGET_SIZE
    )

    # Create data loaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0  # Set to 0 to avoid multiprocessing issues
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0
    )

    # Create model
    num_classes = len(LABELS)
    if model_type == "lenet":
        model = create_lenet_model(num_classes=num_classes)
    elif model_type == "vgg16":
        model = create_vgg16_model(num_classes=num_classes)
    else:
        raise ValueError(f"Unknown model type: {model_type}. Choose from: 'lenet', 'vgg16'")

    model = model.to(device)

    # Loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    # criteria: cross entropy
    if loss_function == "cross_entropy":
        criterion = nn.CrossEntropyLoss()
    else:
        raise ValueError(f"Unknown loss function: {loss_function}.")
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    # Track metrics for visualization
    train_losses = []
    val_losses = []
    train_accs = []
    val_accs = []

    # Training loop
    best_val_acc = 0.0
    best_model_state = None

    print(f"\nStarting training for {num_epochs} epochs...")
    print("=" * 60)

    for epoch in range(num_epochs):
        print(f"\nEpoch {epoch + 1}/{num_epochs}")
        print("-" * 60)

        # Train
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)

        # Validate
        val_loss, val_acc = validate(model, val_loader, criterion, device)

        # Store metrics
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%")
        print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")

        # Save best model
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_model_state = model.state_dict().copy()
            print(f"New best validation accuracy: {best_val_acc:.2f}%")

    # Load best model state back into model
    if best_model_state is not None:
        model.load_state_dict(best_model_state)
        print(f"\nLoaded best model with validation accuracy: {best_val_acc:.2f}%")

    # Save the final model
    save_model(
        model=model,
        model_path=model_save_path,
        metadata={
            'model_type': model_type,
            'best_val_accuracy': best_val_acc,
            'num_epochs': num_epochs,
            'learning_rate': learning_rate,
            'batch_size': batch_size,
            'train_size': len(train_dataset),
            'val_size': len(val_dataset),
            'num_classes': len(LABELS),
            'target_size': TARGET_SIZE,
        }
    )

    # Plot training curves
    plot_training_curves(
        train_losses, val_losses, train_accs, val_accs,
        save_path=plot_save_path
    )

    print("\n" + "=" * 60)
    print("Training completed!")
    print(f"Best validation accuracy: {best_val_acc:.2f}%")
    print(f"Model saved to: {model_save_path}")
    print(f"Training curves saved to: {plot_save_path}")
    print("=" * 60)

train_model(
        base_dir=".",  # Base directory containing char_train/ and char_val/ folders
        model_type="lenet",  # "lenet" or "vgg16"
        loss_function="cross_entropy",  # "cross_entropy" or "ctc"
        batch_size=32,
        num_epochs=15,
        learning_rate=1e-4,
        device='cuda',
        model_save_path="saved_models/lenet_character_classifier.pth",
        plot_save_path="lenet_training_curves.png",
    )

train_model(
        base_dir=".",  # Base directory containing char_train/ and char_val/ folders
        model_type="vgg16",  # "lenet" or "vgg16"
        loss_function="cross_entropy",  # "cross_entropy" or "ctc"
        batch_size=32,
        num_epochs=15,
        learning_rate=1e-4,
        device='cuda',
        model_save_path="saved_models/vgg16_character_classifier.pth",
        plot_save_path="vgg16_training_curves.png",
    )

"""# Training Sequential Classifier"""

# Unzips the zipped training and validation sets
import zipfile

for zip_file in ['word_train.zip', 'word_val.zip']:
    with zipfile.ZipFile(zip_file, 'r') as z:
        z.extractall('.')

LABELS = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
]

"""
Training pipeline for CRNN sequence recognition on word images.
Images are named as: {word}_{number}.png where {word} is the ground truth label.
"""
import os
import sys
import torch
import torch.nn as nn

import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
from typing import List
from tqdm import tqdm
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt


# fixed height but variable width
TARGET_HEIGHT = 32  # Standard height for text recognition


class WordSequenceDataset(Dataset):

    def __init__(
        self,
        base_dir: str,
        split: str = "train",  # "train" or "val"
        target_height: int = TARGET_HEIGHT,
        transform=None,
    ):

        self.base_dir = base_dir
        self.split = split
        self.target_height = target_height
        self.transform = transform

        # Create character to index mapping (for CTC, blank is typically last)
        self.char_to_idx = {char: idx for idx, char in enumerate(LABELS)}
        self.idx_to_char = {idx: char for char, idx in self.char_to_idx.items()}
        self.num_classes = len(LABELS) + 1  # +1 for CTC blank token
        self.blank_idx = len(LABELS)  # Blank token index

        # Load all images and labels
        self.image_paths = []
        self.labels = []
        self._load_images()

        print(f"Loaded {len(self.image_paths)} images for {split} split")
        print(f"Number of character classes: {len(LABELS)} (+ 1 blank = {self.num_classes})")

        # Show some example labels
        if len(self.labels) > 0:
            print("Sample labels:")
            for i in range(min(5, len(self.labels))):
                label_str = ''.join([self.idx_to_char[idx] for idx in self.labels[i]])
                print(f"  {label_str}")

    def _load_images(self):
        """Load all images from the folder structure."""
        split_dir = os.path.join(self.base_dir, f"word_{self.split}")

        if not os.path.exists(split_dir):
            raise ValueError(f"Directory {split_dir} does not exist")

        # Get all PNG files
        image_files = [f for f in os.listdir(split_dir)
                      if f.lower().endswith('.png')]

        for img_file in sorted(image_files):
            img_path = os.path.join(split_dir, img_file)

            # Extract label from filename: {word}_{number}.png -> {word}
            # Split by underscore and take everything except the last part (number)
            name_without_ext = os.path.splitext(img_file)[0]
            parts = name_without_ext.split('_')

            if len(parts) < 2:
                print(f"Warning: Could not parse label from filename {img_file}, skipping...")
                continue

            # Join all parts except the last one (which is the number)
            word = '_'.join(parts[:-1])

            # Encode word as sequence of character indices
            label_seq = []
            for char in word:
                if char in self.char_to_idx:
                    label_seq.append(self.char_to_idx[char])
                else:
                    # Skip characters not in our label set
                    print(f"Warning: Character '{char}' not in LABELS, skipping from word '{word}'")

            if len(label_seq) == 0:
                print(f"Warning: No valid characters in word '{word}', skipping...")
                continue

            self.image_paths.append(img_path)
            self.labels.append(label_seq)

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        """
        returns:            image: Tensor of shape (1, H, W) - grayscale word image (variable width)
            label: List of character indices (ground truth sequence)
            label_length: Length of the label sequence
        """
        import cv2

        img_path = self.image_paths[idx]
        label_seq = self.labels[idx]

        # Load image
        img = load_img(img_path)
        if img is None:
            # If image fails to load, return a black image
            img = np.zeros((self.target_height, 100), dtype=np.uint8)
        else:
            # Convert to grayscale if needed
            if len(img.shape) == 3:
                img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

            # Ensure binary format (0 or 255)
            if img.max() <= 1:
                img = (img * 255).astype(np.uint8)

            # Resize to target height while maintaining aspect ratio
            h, w = img.shape[:2]
            scale = self.target_height / h
            new_w = int(w * scale)
            img = cv2.resize(img, (new_w, self.target_height), interpolation=cv2.INTER_AREA)

        # Normalize to [0, 1]
        img_normalized = img.astype(np.float32) / 255.0

        # Convert to tensor and add channel dimension: (H, W) -> (1, H, W)
        image_tensor = torch.from_numpy(img_normalized).unsqueeze(0)

        # Apply transforms if provided
        if self.transform:
            image_tensor = self.transform(image_tensor)

        # Convert label to tensor
        label_tensor = torch.tensor(label_seq, dtype=torch.long)

        return image_tensor, label_tensor, len(label_seq)

# Custom collate function for batching the data
def collate_fn(batch):

    images, labels, label_lengths = zip(*batch)

    # Get maximum width for padding
    max_width = max(img.shape[2] for img in images)

    # Pad images to same width
    padded_images = []
    image_widths = []
    for img in images:
        _, h, w = img.shape
        image_widths.append(w)
        # Pad right side with zeros
        padding = max_width - w
        padded_img = torch.nn.functional.pad(img, (0, padding), mode='constant', value=0)
        padded_images.append(padded_img)

    # Stack images
    images_tensor = torch.stack(padded_images)

    # Concatenate all labels
    labels_tensor = torch.cat(labels)

    # Convert to tensors
    label_lengths_tensor = torch.tensor(label_lengths, dtype=torch.long)
    image_widths_tensor = torch.tensor(image_widths, dtype=torch.long)

    return images_tensor, labels_tensor, label_lengths_tensor, image_widths_tensor


def calculate_input_lengths(image_widths: torch.Tensor) -> torch.Tensor:

    return (image_widths // 4).long()


def train_epoch(model, dataloader, criterion, optimizer, device):
    #Train for one epoch
    model.train()
    running_loss = 0.0
    total_samples = 0

    for images, labels, label_lengths, image_widths in tqdm(dataloader, desc="Training"):
        images = images.to(device)
        labels = labels.to(device)
        label_lengths = label_lengths.to(device)
        image_widths = image_widths.to(device)

        # Calculate input lengths (sequence length from CNN output)
        input_lengths = calculate_input_lengths(image_widths)
        input_lengths = input_lengths.to(device)

        # Forward pass
        optimizer.zero_grad()
        logits = model(images)  # Shape: (W, B, num_classes)

        # CTC loss expects log_probs in shape (T, N, C) where:
        # T = sequence length, N = batch size, C = num classes
        log_probs = nn.functional.log_softmax(logits, dim=2)

        # Calculate loss
        loss = criterion(log_probs, labels, input_lengths, label_lengths)

        # Backward pass
        loss.backward()
        optimizer.step()

        # Stastatstistics
        running_loss += loss.item()
        total_samples += images.size(0)

    epoch_loss = running_loss / len(dataloader)
    return epoch_loss


def calculate_edit_distance(s1: str, s2: str) -> int:
    # Levenshtein distance
    m, n = len(s1), len(s2)

    # Create a matrix to store distances
    dp = [[0] * (n + 1) for _ in range(m + 1)]

    # Initialize base cases
    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j

    # Fill the matrix
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if s1[i - 1] == s2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = min(
                    dp[i - 1][j] + 1,      # deletion
                    dp[i][j - 1] + 1,      # insertion
                    dp[i - 1][j - 1] + 1   # substitution
                )

    return dp[m][n]


def calculate_cer(predicted: str, reference: str) -> float:

    # CER = Edit Distance / Length of Reference

    if len(reference) == 0:
        return 1.0 if len(predicted) > 0 else 0.0

    edit_dist = calculate_edit_distance(predicted, reference)
    return edit_dist / len(reference)


def validate(model, dataloader, criterion, device, idx_to_char):
    # validate model w/ CER
    model.eval()
    running_loss = 0.0
    total_samples = 0
    total_cer = 0.0
    total_chars = 0

    with torch.no_grad():
        for images, labels, label_lengths, image_widths in tqdm(dataloader, desc="Validating"):
            images = images.to(device)
            labels = labels.to(device)
            label_lengths = label_lengths.to(device)
            image_widths = image_widths.to(device)

            # Calculate input lengths
            input_lengths = calculate_input_lengths(image_widths)
            input_lengths = input_lengths.to(device)

            # Forward pass
            logits = model(images)
            log_probs = nn.functional.log_softmax(logits, dim=2)

            # Calculate loss
            loss = criterion(log_probs, labels, input_lengths, label_lengths)

            running_loss += loss.item()
            total_samples += images.size(0)

            # Decode predictions for CER calculation
            # Use greedy decoding (argmax at each timestep)
            predictions = log_probs.argmax(dim=2)  # Shape: (W, B)
            predictions = predictions.permute(1, 0)  # Shape: (B, W)

            # Decode predictions (remove blanks and consecutive duplicates)
            batch_size = predictions.size(0)
            for i in range(batch_size):
                pred_seq = predictions[i].cpu().numpy()
                # Remove blanks and consecutive duplicates
                decoded = []
                prev = None
                for idx in pred_seq:
                    if idx != len(LABELS) and idx != prev:  # Not blank and not duplicate
                        decoded.append(idx_to_char[idx])
                    prev = idx
                pred_str = ''.join(decoded)

                # Get ground truth
                start_idx = sum(label_lengths[:i].cpu().numpy())
                end_idx = start_idx + label_lengths[i].cpu().item()
                gt_seq = labels[start_idx:end_idx].cpu().numpy()
                gt_str = ''.join([idx_to_char[idx] for idx in gt_seq])

                # Calculate CER for this prediction
                cer = calculate_cer(pred_str, gt_str)
                total_cer += cer * len(gt_str)  # Weight by reference length
                total_chars += len(gt_str)

    epoch_loss = running_loss / len(dataloader)
    avg_cer = total_cer / total_chars if total_chars > 0 else 1.0
    char_accuracy = (1.0 - avg_cer) * 100.0  # Convert to percentage

    return epoch_loss, avg_cer, char_accuracy


def plot_training_curves(
    train_losses: List[float],
    val_losses: List[float],
    val_accs: List[float],
    save_path: str = "training_curves_seq.png"
):
    epochs = range(1, len(train_losses) + 1)

    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    # Plot loss
    ax1.plot(epochs, train_losses, 'b-', label='Training Loss', linewidth=2)
    ax1.plot(epochs, val_losses, 'r-', label='Validation Loss', linewidth=2)
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('Loss', fontsize=12)
    ax1.set_title('Training and Validation Loss', fontsize=14)
    ax1.legend(fontsize=11)
    ax1.grid(True, alpha=0.3)

    # Plot accuracy
    ax2.plot(epochs, val_accs, 'g-', label='Validation Accuracy', linewidth=2)
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Accuracy (%)', fontsize=12)
    ax2.set_title('Validation Accuracy', fontsize=14)
    ax2.legend(fontsize=11)
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()

    # Save plot
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\nTraining curves saved to: {save_path}")

    plt.close()


def save_model(model: nn.Module, model_path: str, metadata: dict = None):
    # Save a PyTorch model with optional metadata
    os.makedirs(os.path.dirname(model_path), exist_ok=True)

    save_dict = {
        'model_state_dict': model.state_dict(),
        'metadata': metadata or {}
    }

    torch.save(save_dict, model_path)
    print(f"Model saved to: {model_path}")


def train_model(
    base_dir: str,
    batch_size: int,# = 16,
    num_epochs: int,# = 20,
    learning_rate: float,# = 1e-4,
    device,
    model_save_path: str,# = "saved_models/crnn_word_classifier.pth",
    plot_save_path: str,# = "training_curves_seq.png",
    rnn_hidden_size: int,# = 256,
    cnn_out_channels: int,# = 512,
    early_stopping_patience: int,# = 5,
    early_stopping_min_delta: float# = 0.0,
):

    # Set device
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(device)
    print(f"Using device: {device}")

    # Create datasets
    print("\nLoading training dataset...")
    train_dataset = WordSequenceDataset(
        base_dir=base_dir,
        split="train",
        target_height=TARGET_HEIGHT
    )

    print("\nLoading validation dataset...")
    val_dataset = WordSequenceDataset(
        base_dir=base_dir,
        split="val",
        target_height=TARGET_HEIGHT
    )

    # Create data loaders with custom collate function
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,  # Set to 0 to avoid multiprocessing issues
        collate_fn=collate_fn
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        collate_fn=collate_fn
    )

    # Create model
    num_classes = len(LABELS) + 1  # +1 for blank token
    model = CRNN(
        num_classes=num_classes,
        rnn_hidden_size=rnn_hidden_size,
        cnn_out_channels=cnn_out_channels,
        dropout=0.35,
        num_rnn_layers=1
    )
    model = model.to(device)

    # Loss function and optimizer
    criterion = nn.CTCLoss(blank=len(LABELS), reduction='mean', zero_infinity=True)
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    # Create idx_to_char mapping for validation
    idx_to_char = {idx: char for idx, char in enumerate(LABELS)}
    idx_to_char[len(LABELS)] = '<blank>'  # Blank token

    # Track metrics for visualization
    train_losses = []
    val_losses = []
    val_cers = []  # Character Error Rates
    val_accs = []  # Character-level accuracies (1 - CER)

    # Training loop with early stopping
    best_val_acc = 0.0
    best_val_cer = 1.0
    best_model_state = None
    epochs_without_improvement = 0

    print(f"\nStarting training for {num_epochs} epochs...")
    if early_stopping_patience > 0:
        print(f"Early stopping enabled: patience={early_stopping_patience}, min_delta={early_stopping_min_delta}")
    print("=" * 60)

    for epoch in range(num_epochs):
        print(f"\nEpoch {epoch + 1}/{num_epochs}")
        print("-" * 60)

        # Train
        train_loss = train_epoch(model, train_loader, criterion, optimizer, device)

        # Validate (returns loss, CER, and character accuracy)
        val_loss, val_cer, val_acc = validate(model, val_loader, criterion, device, idx_to_char)

        # Store metrics
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        val_cers.append(val_cer)
        val_accs.append(val_acc)

        print(f"Train Loss: {train_loss:.4f}")
        print(f"Val Loss: {val_loss:.4f}, Val CER: {val_cer:.4f}, Val Char Acc: {val_acc:.2f}%")

        # Check for improvement (using character accuracy, higher is better)
        if val_acc > best_val_acc + early_stopping_min_delta:
            best_val_acc = val_acc
            best_val_cer = val_cer
            best_model_state = model.state_dict().copy()
            epochs_without_improvement = 0
            print(f"New best validation: CER={best_val_cer:.4f}, Char Acc={best_val_acc:.2f}%")
        else:
            epochs_without_improvement += 1
            if early_stopping_patience > 0:
                print(f"No improvement for {epochs_without_improvement} epochs (best CER: {best_val_cer:.4f}, best Acc: {best_val_acc:.2f}%)")

        # Early stopping check
        if early_stopping_patience > 0 and epochs_without_improvement >= early_stopping_patience:
            print(f"\nEarly stopping after {epoch + 1} epochs")
            print(f"No improvement in validation accuracy for {early_stopping_patience} consecutive epochs.")
            break

    # Load best model state back into model
    if best_model_state is not None:
        model.load_state_dict(best_model_state)
        print(f"\nLoaded best model: CER={best_val_cer:.4f}, Char Acc={best_val_acc:.2f}%")

    # Save the final model
    save_model(
        model=model,
        model_path=model_save_path,
        metadata={
            'model_type': 'CRNN',
            'best_val_cer': best_val_cer,
            'best_val_char_accuracy': best_val_acc,
            'num_epochs': num_epochs,
            'learning_rate': learning_rate,
            'batch_size': batch_size,
            'train_size': len(train_dataset),
            'val_size': len(val_dataset),
            'num_classes': num_classes,
            'target_height': TARGET_HEIGHT,
            'rnn_hidden_size': rnn_hidden_size,
            'cnn_out_channels': cnn_out_channels,
            'early_stopping_patience': early_stopping_patience,
            'early_stopping_min_delta': early_stopping_min_delta,
            'actual_epochs_trained': len(train_losses),
        }
    )

    # Plot training curves
    plot_training_curves(
        train_losses, val_losses, val_accs,
        save_path=plot_save_path
    )

    print("\n" + "=" * 60)
    print("Training completed!")
    print(f"Total epochs trained: {len(train_losses)}")
    print(f"Best validation CER: {best_val_cer:.4f}")
    print(f"Best validation character accuracy: {best_val_acc:.2f}%")
    print(f"Model saved to: {model_save_path}")
    print(f"Training curves saved to: {plot_save_path}")
    print("=" * 60)

train_model(
        base_dir=".",  # Base directory containing word_train/ and word_val/ folders
        batch_size=16,
        num_epochs=20,
        learning_rate=1e-4,
        device='cuda',
        model_save_path="saved_models/crnn_word_classifier.pth",
        plot_save_path="crnn_training_curves.png",
        rnn_hidden_size=256,
        cnn_out_channels=512,
        early_stopping_patience=5,  # Stop if no improvement for 5 epochs
        early_stopping_min_delta=0.05
    )

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# cp -r /content/saved_models /content/drive/MyDrive/
# cp /content/lenet_training_curves.png /content/drive/MyDrive/
# cp /content/vgg16_training_curves.png /content/drive/MyDrive/
# cp /content/crnn_training_curves.png /content/drive/MyDrive/